# Qdrant Configuration for Agentic Platform
# Simplified configuration to avoid duplicate field issues

log_level: INFO

service:
  http_port: 6333
  grpc_port: 6334
  enable_cors: true
  max_request_size_mb: 32
  max_workers: 4

storage:
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/snapshots
  temp_path: /tmp

# Clustering configuration for future scaling
cluster:
  enabled: false

# TLS configuration (to be enabled in production)
tls:
  cert: ""
  key: ""
  ca_cert: ""
